/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent { 'title' : string, 'body' : string }
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface HeroContent {
  'title' : string,
  'ctaText' : string,
  'subtitle' : string,
}
export interface ServiceContent {
  'id' : string,
  'title' : string,
  'description' : string,
}
export interface TestimonialContent {
  'id' : string,
  'role' : string,
  'quote' : string,
  'author' : string,
}
export interface UserProfile { 'name' : string }
export interface _SERVICE {
  'addService' : ActorMethod<[ServiceContent], undefined>,
  'addTestimonial' : ActorMethod<[TestimonialContent], undefined>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getAllServices' : ActorMethod<[], Array<ServiceContent>>,
  'getAllTestimonials' : ActorMethod<[], Array<TestimonialContent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getHeroContent' : ActorMethod<[], HeroContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'removeService' : ActorMethod<[string], undefined>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServices' : ActorMethod<[string], Array<ServiceContent>>,
  'updateAboutContent' : ActorMethod<[AboutContent], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateHeroContent' : ActorMethod<[HeroContent], undefined>,
  'updateService' : ActorMethod<[string, ServiceContent], undefined>,
  'updateTestimonial' : ActorMethod<[string, TestimonialContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];