/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent { 'title' : string, 'body' : string }
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'category' : string,
}
export interface HeroContent {
  'title' : string,
  'ctaText' : string,
  'subtitle' : string,
}
export interface ServiceContent {
  'id' : string,
  'title' : string,
  'description' : string,
}
export interface TestimonialContent {
  'id' : string,
  'role' : string,
  'quote' : string,
  'author' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'addService' : ActorMethod<[ServiceContent], undefined>,
  'addTestimonial' : ActorMethod<[TestimonialContent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllServices' : ActorMethod<[], Array<ServiceContent>>,
  'getAllTestimonials' : ActorMethod<[], Array<TestimonialContent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getGalleryItemsByCategory' : ActorMethod<[string], Array<GalleryItem>>,
  'getHeroContent' : ActorMethod<[], HeroContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGalleryItem' : ActorMethod<[string], undefined>,
  'removeService' : ActorMethod<[string], undefined>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServices' : ActorMethod<[string], Array<ServiceContent>>,
  'updateAboutContent' : ActorMethod<[AboutContent], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateGalleryItem' : ActorMethod<[string, GalleryItem], undefined>,
  'updateHeroContent' : ActorMethod<[HeroContent], undefined>,
  'updateService' : ActorMethod<[string, ServiceContent], undefined>,
  'updateTestimonial' : ActorMethod<[string, TestimonialContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];