/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const TestimonialContent = IDL.Record({
  'id' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'author' : IDL.Text,
});
export const AboutContent = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const HeroContent = IDL.Record({
  'title' : IDL.Text,
  'ctaText' : IDL.Text,
  'subtitle' : IDL.Text,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func([ServiceContent], [], []),
  'addTestimonial' : IDL.Func([TestimonialContent], [], []),
  'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(ServiceContent)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(TestimonialContent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getHeroContent' : IDL.Func([], [HeroContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'removeService' : IDL.Func([IDL.Text], [], []),
  'removeTestimonial' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(ServiceContent)], ['query']),
  'updateAboutContent' : IDL.Func([AboutContent], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateHeroContent' : IDL.Func([HeroContent], [], []),
  'updateService' : IDL.Func([IDL.Text, ServiceContent], [], []),
  'updateTestimonial' : IDL.Func([IDL.Text, TestimonialContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const TestimonialContent = IDL.Record({
    'id' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'author' : IDL.Text,
  });
  const AboutContent = IDL.Record({ 'title' : IDL.Text, 'body' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const HeroContent = IDL.Record({
    'title' : IDL.Text,
    'ctaText' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  
  return IDL.Service({
    'addService' : IDL.Func([ServiceContent], [], []),
    'addTestimonial' : IDL.Func([TestimonialContent], [], []),
    'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(ServiceContent)], ['query']),
    'getAllTestimonials' : IDL.Func(
        [],
        [IDL.Vec(TestimonialContent)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getHeroContent' : IDL.Func([], [HeroContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'removeService' : IDL.Func([IDL.Text], [], []),
    'removeTestimonial' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchServices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceContent)],
        ['query'],
      ),
    'updateAboutContent' : IDL.Func([AboutContent], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateHeroContent' : IDL.Func([HeroContent], [], []),
    'updateService' : IDL.Func([IDL.Text, ServiceContent], [], []),
    'updateTestimonial' : IDL.Func([IDL.Text, TestimonialContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };